# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)
xcversion(version: "14.0.1")

scheme = "Pain App"
project = "Pain App.xcodeproj"

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: scheme)
  end

  desc  "Test the application"
  private_lane :test_app do
    # run tests
    scan
    trainer(
      path:"results/"
    )
    
    xcov(project: project,
      scheme: scheme,
      configuration: "Debug",
      html_report: true,
      minimum_coverage_percentage: 0.0,
      ignore_file_path: "../.xcovignore",
      include_targets: "Pain App.app"
    )
    # Run swiftlint to detect code smells (you might need to specify the executable path
    swiftlint(reporter: "junit", output_file: "./reports/swiftlint.xml", ignore_exit_status: true)
  end

  desc "Run tests"
  lane :run_tests do
    # Test the app and publish the reports
    test_app
  end

end
